// Core Game Genres
export const CORE_GENRES = [
    "Puzzle",
    "Action-Adventure",
    "Arcade",
    "Shooter",
    "Platformer",
    "Visual Novel",
    "Roguelike",
    "Sandbox",
    "Action RPG",
    "Point & Click",
    "Action Roguelike",
    "Interactive Fiction",
    "Turn-Based Strategy",
    "Tabletop",
    "Dating Sim",
    "Education",
    "Walking Simulator",
    "JRPG",
    "Party-Based RPG",
    "Card Game",
    "Life Sim",
    "Design & Illustration",
    "Strategy RPG",
    "Utilities",
    "Board Game",
    "RTS",
    "Tower Defense",
    "City Builder",
    "Web Publishing",
    "Beat 'em up",
    "Automobile Sim",
    "2D Fighter",
    "Rhythm",
    "Farming Sim",
    "3D Fighter",
    "Word Game",
    "eSports",
    "Colony Sim",
    "Auto Battler",
    "Grand Strategy",
    "Space Sim",
    "Animation & Modeling",
    "Battle Royale",
    "MMORPG",
    "Audio Production",
    "God Game",
    "Video Production",
    "4X",
    "MOBA",
    "Trivia",
    "Photo Editing"
] as const;

// Themes & Moods
export const THEME_GENRES = [
    "Atmospheric",
    "Fantasy",
    "Relaxing",
    "Funny",
    "Horror",
    "Sci-fi",
    "Family Friendly",
    "Retro",
    "Mystery",
    "Dark",
    "Survival",
    "Comedy",
    "Psychological Horror",
    "Medieval",
    "Sports",
    "Old School",
    "Magic",
    "Management",
    "Building",
    "Tactical",
    "Drama",
    "Racing",
    "Space",
    "Futuristic",
    "Crafting",
    "Logic",
    "Romance",
    "Dark Fantasy",
    "Emotional",
    "Survival Horror",
    "Nature",
    "1990's",
    "1980s",
    "Surreal",
    "Post-apocalyptic",
    "War",
    "Zombies",
    "Historical",
    "Stealth",
    "Investigation",
    "Lore-Rich",
    "Military",
    "LGBTQ+",
    "Economy",
    "Thriller",
    "Psychological",
    "Detective",
    "Cyberpunk",
    "Dark Humor",
    "Demons",
    "Aliens",
    "Robots",
    "Supernatural",
    "Driving",
    "Comic Book",
    "Modern",
    "Dystopian",
    "Psychedelic",
    "Loot",
    "Artificial Intelligence",
    "Cats",
    "Flight",
    "Alternate History",
    "Memes",
    "Parkour",
    "Mythology",
    "Crime",
    "Game Development",
    "Destruction",
    "Capitalism",
    "Automation",
    "Philosophical",
    "Dark Comedy",
    "Cooking",
    "Noir",
    "Lovecraftian",
    "Swordplay",
    "Science",
    "America",
    "Dragons",
    "Parody",
    "Agriculture",
    "World War II",
    "Conspiracy",
    "Gothic",
    "Martial Arts",
    "Satire",
    "Underground",
    "Mechs",
    "Dog",
    "Fishing",
    "Mining",
    "Pirates",
    "Steampunk",
    "Time Travel",
    "Transportation",
    "Vampire",
    "Political",
    "Underwater",
    "Tanks",
    "Ninja",
    "Hunting",
    "Otome",
    "Trains",
    "Gambling",
    "Western",
    "Dinosaurs",
    "Hacking",
    "Faith",
    "Programming",
    "Superhero",
    "Politics",
    "Assassin",
    "Diplomacy",
    "Naval",
    "Snow",
    "Heist",
    "Archery",
    "Sailing",
    "Cold War",
    "Horses",
    "Football (Soccer)",
    "Foreign",
    "Offroad",
    "Transhumanism",
    "Sniper",
    "Illuminati",
    "Boxing",
    "Jet",
    "Werewolves",
    "Mars",
    "Motorbike",
    "Golf",
    "World War I",
    "Bikes",
    "Basketball",
    "Baseball",
    "Rome",
    "Submarine",
    "LEGO",
    "Skateboarding",
    "Mini Golf",
    "Wrestling",
    "Football (American)",
    "Pool",
    "Tennis",
    "Skating",
    "Cycling",
    "Motocross",
    "Warhammer 40K",
    "Hockey",
    "Bowling",
    "Lemmings",
    "Skiing",
    "Snowboarding",
    "BMX",
    "ATV"
] as const;

// Top-Level Genres
export const TOP_LEVEL_GENRES = [
    "Indie",
    "Action",
    "Casual",
    "Adventure",
    "Simulation",
    "RPG",
    "Strategy",
    "Action-Adventure",
    "Sports",
    "Racing",
    "Software"
] as const;

// Visual & Viewpoint
export const VISUAL_GENRES = [
    "2D",
    "3D",
    "Colorful",
    "Pixel Graphics",
    "Cute",
    "First-Person",
    "Anime",
    "Stylized",
    "Third Person",
    "Top-Down",
    "Realistic",
    "Cartoony",
    "Hand-drawn",
    "Minimalist",
    "VR",
    "Cartoon",
    "Cinematic",
    "Text-Based",
    "2.5D",
    "Isometric",
    "Abstract",
    "Comic Book",
    "Psychedelic",
    "Noir",
    "3D Vision",
    "Split Screen",
    "Voxel",
    "FMV",
    "Beautiful",
    "360 Video"
] as const;

// Combine all genres for main validation
export const GAME_GENRES = [
    ...CORE_GENRES,
    ...THEME_GENRES,
    ...TOP_LEVEL_GENRES,
    ...VISUAL_GENRES
] as const;

export type GameGenre = typeof GAME_GENRES[number];

// Helper functions
export const isValidGenre = (genre: string): genre is GameGenre => {
    return GAME_GENRES.includes(genre as GameGenre);
};

export const filterValidGenres = (genres: string[]): GameGenre[] => {
    return genres.filter(isValidGenre);
};

// Genre categories for better organization
export const GENRE_CATEGORIES = {
    // Core gameplay categories
    ACTION: ["Action", "Shooter", "Action-Adventure", "Action RPG", "Beat 'em up", "2D Fighter", "3D Fighter"],
    STRATEGY: ["Strategy", "Turn-Based Strategy", "RTS", "Grand Strategy", "Tower Defense", "4X", "Strategy RPG"],
    RPG: ["RPG", "Action RPG", "JRPG", "Party-Based RPG", "Strategy RPG", "MMORPG"],
    SIMULATION: ["Simulation", "Life Sim", "Automobile Sim", "Farming Sim", "Space Sim", "Colony Sim", "City Builder"],
    PUZZLE: ["Puzzle", "Word Game", "Logic"],
    ADVENTURE: ["Adventure", "Action-Adventure", "Point & Click", "Walking Simulator"],

    // Themes
    SCI_FI: ["Sci-fi", "Space", "Futuristic", "Cyberpunk", "Aliens", "Robots", "Mars"],
    FANTASY: ["Fantasy", "Magic", "Dragons", "Dark Fantasy", "Medieval"],
    HORROR: ["Horror", "Psychological Horror", "Survival Horror", "Dark", "Zombies", "Demons"],

    // Multiplayer
    MULTIPLAYER: ["MOBA", "Battle Royale", "eSports", "MMORPG"],

    // Creative
    CREATIVE: ["Design & Illustration", "Animation & Modeling", "Audio Production", "Video Production"],

    // Sports & Racing
    SPORTS: ["Sports", "Racing", "Football (Soccer)", "Basketball", "Baseball", "Golf", "Tennis"],

    // Casual
    CASUAL: ["Casual", "Arcade", "Card Game", "Board Game", "Trivia", "Dating Sim"]
} as const;

// Map common CSV genre terms to our standardized genres
export const GENRE_MAPPING: { [key: string]: GameGenre | null } = {
    // Common mappings from CSV data
    'FPS': 'Shooter',
    'SHOOTER': 'Shooter',
    'MULTIPLAYER': null, // Not a genre, it's a feature
    'COMPETITIVE': 'eSports',
    'RPG': 'RPG',
    'STRATEGY': 'Strategy',
    'SIMULATION': 'Simulation',
    'PUZZLE': 'Puzzle',
    'PLATFORMER': 'Platformer',
    'ADVENTURE': 'Adventure',
    'RACING': 'Racing',
    'SPORTS': 'Sports',
    'FIGHTING': '2D Fighter',
    'HORROR': 'Horror',
    'SURVIVAL': 'Survival',
    'SANDBOX': 'Sandbox',
    'ROGUELIKE': 'Roguelike',
    'ARCADE': 'Arcade',
    'VISUAL_NOVEL': 'Visual Novel',
    'CARD': 'Card Game',
    'BOARD': 'Board Game',
    'RHYTHM': 'Rhythm',
    'TOWER_DEFENSE': 'Tower Defense',
    'RTS': 'RTS',
    'MMORPG': 'MMORPG',
    'MOBA': 'MOBA',
    'BATTLE_ROYALE': 'Battle Royale',

    // Additional mappings
    'SCIFI': 'Sci-fi',
    'SCI_FI': 'Sci-fi',
    'FANTASY': 'Fantasy',
    'MEDIEVAL': 'Medieval',
    'FUTURISTIC': 'Futuristic',
    'POST_APOCALYPTIC': 'Post-apocalyptic',
    'CYBERPUNK': 'Cyberpunk',
    'STEAMPUNK': 'Steampunk'
};

// Export commonly used genre sets
export const POPULAR_GENRES = [
    "Action",
    "Adventure",
    "RPG",
    "Strategy",
    "Simulation",
    "Puzzle",
    "Shooter",
    "Platformer",
    "Racing",
    "Sports"
] as const;

export const STEAM_POPULAR_GENRES = [
    "Action",
    "Indie",
    "Casual",
    "Adventure",
    "Strategy",
    "Simulation",
    "RPG",
    "Racing",
    "Sports",
    "Shooter"
] as const;